database_path = "nq.db"
password = "password"

### Optional path to user-provided templates
# template_path = "templates"

### Optional path to user-provided asset directory. Must not have symlinks or subdirectories.
# asset_path = "assets"

### (recommended) IP address header to ratelimit by. Directly used as the limit key, so IP hashes are fine.
# ip_header = "x-real-ip"

### How long IPs must wait between auth tries. Defaults to 30s.
# auth_cooldown = 30

### How long IPs must wait before asking another question. Defaults to 300s.
# ask_cooldown = 300

### Alternate bind address
# bind_address = "0.0.0.0:8080"

### Used to redirect users in Mastodon posts, if set.
# root_url = "https://example.com"


### Optional Mastodon API integration to autopost responses
# Generate an API token at https://your.domain/settings/applications
# It only needs `write:statuses`
# Uncomment all the following three lines to enable
#[mastodon]
#api_token = ""
#api_url = "https://mastodon.social" # No trailing slash!!

### Optional ntfy.sh integration for push notifs when new question is asked
# See https://ntfy.sh/docs/publish/#access-tokens
# Generate token at https://ntfy.sh/account
#[ntfy]
#api_token = ""
#api_url = "https://ntfy.sh/topic" # No trailing slash!!