bind_address = "0.0.0.0:8080"
database_path = "nq.db"
password = "password"
template_path = "templates"

### Optional Mastodon API integration to autopost responses
# Generate an API token at https://your.domain/settings/applications
# It only needs `write:statuses`
# Uncomment all the following three lines to enable
#[mastodon]
#api_token = ""
#api_url = "https://mastodon.social" # No trailing slash!!

### Optional ntfy.sh integration for push notifs when new question is asked
# See https://ntfy.sh/docs/publish/#access-tokens
# Generate token at https://ntfy.sh/account
#[ntfy]
#api_token = ""
#api_url = "https://ntfy.sh" # No trailing slash!!