database_path = "nq.db"
password = "password"
mastodon_api_token =  "" # https://example.com/settings/applications
mastodon_api_url = "https://mastodon.social" # No trailing slash!!
template_path = "templates"
